### Install and Setup

In [36]:
pip install google-genai pandas sklearn jsonschema tqdm

Collecting google-genai
  Downloading google_genai-1.53.0-py3-none-any.whl (262 kB)
Requirement already satisfied: pandas in c:\users\hp\appdata\local\programs\python\python310\lib\site-packages (2.3.3)
Collecting sklearn
  Downloading sklearn-0.0.post12.tar.gz (2.6 kB)
  Downloading sklearn-0.0.post11.tar.gz (3.6 kB)
  Downloading sklearn-0.0.post10.tar.gz (3.6 kB)
  Downloading sklearn-0.0.post9.tar.gz (3.6 kB)
  Downloading sklearn-0.0.post7.tar.gz (3.6 kB)
  Downloading sklearn-0.0.post5.tar.gz (3.7 kB)
  Downloading sklearn-0.0.post4.tar.gz (3.6 kB)
  Downloading sklearn-0.0.post1.tar.gz (3.6 kB)
  Downloading sklearn-0.0.tar.gz (1.1 kB)
Collecting jsonschema
  Using cached jsonschema-4.25.1-py3-none-any.whl (90 kB)
Requirement already satisfied: tqdm in c:\users\hp\appdata\local\programs\python\python310\lib\site-packages (4.67.1)
Requirement already satisfied: google-auth[requests]<3.0.0,>=2.14.1 in c:\users\hp\appdata\local\programs\python\python310\lib\site-packages (from google-genai) (2.43.0)
Requirement already satisfied: pydantic<3.0.0,>=2.9.0 in c:\users\hp\appdata\local\programs\python\python310\lib\site-packages (from google-genai) (2.12.5)
Collecting websockets<15.1.0,>=13.0.0
  Downloading websockets-15.0.1-cp310-cp310-win_amd64.whl (176 kB)
Collecting tenacity<9.2.0,>=8.2.3
  Downloading tenacity-9.1.2-py3-none-any.whl (28 kB)
Requirement already satisfied: requests<3.0.0,>=2.28.1 in c:\users\hp\appdata\local\programs\python\python310\lib\site-packages (from google-genai) (2.32.5)
Requirement already satisfied: typing-extensions<5.0.0,>=4.11.0 in c:\users\hp\appdata\local\programs\python\python310\lib\site-packages (from google-genai) (4.15.0)
Collecting httpx<1.0.0,>=0.28.1
  Downloading httpx-0.28.1-py3-none-any.whl (73 kB)
Collecting anyio<5.0.0,>=4.8.0
  Downloading anyio-4.12.0-py3-none-any.whl (113 kB)
Requirement already satisfied: pytz>=2020.1 in c:\users\hp\appdata\local\programs\python\python310\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\hp\appdata\local\programs\python\python310\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\hp\appdata\local\programs\python\python310\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: numpy>=1.22.4 in c:\users\hp\appdata\local\programs\python\python310\lib\site-packages (from pandas) (2.1.2)
Requirement already satisfied: scikit-learn in c:\users\hp\appdata\local\programs\python\python310\lib\site-packages (from sklearn) (1.7.2)
Collecting rpds-py>=0.7.1
  Downloading rpds_py-0.30.0-cp310-cp310-win_amd64.whl (235 kB)
Collecting jsonschema-specifications>=2023.03.6
  Using cached jsonschema_specifications-2025.9.1-py3-none-any.whl (18 kB)
Collecting attrs>=22.2.0
  Using cached attrs-25.4.0-py3-none-any.whl (67 kB)
Collecting referencing>=0.28.4
  Using cached referencing-0.37.0-py3-none-any.whl (26 kB)
Requirement already satisfied: colorama in c:\users\hp\appdata\roaming\python\python310\site-packages (from tqdm) (0.4.6)
Requirement already satisfied: idna>=2.8 in c:\users\hp\appdata\local\programs\python\python310\lib\site-packages (from anyio<5.0.0,>=4.8.0->google-genai) (3.11)
Requirement already satisfied: exceptiongroup>=1.0.2 in c:\users\hp\appdata\roaming\python\python310\site-packages (from anyio<5.0.0,>=4.8.0->google-genai) (1.3.0)
Requirement already satisfied: cachetools<7.0,>=2.0.0 in c:\users\hp\appdata\local\programs\python\python310\lib\site-packages (from google-auth[requests]<3.0.0,>=2.14.1->google-genai) (6.2.2)
Requirement already satisfied: pyasn1-modules>=0.2.1 in c:\users\hp\appdata\local\programs\python\python310\lib\site-packages (from google-auth[requests]<3.0.0,>=2.14.1->google-genai) (0.4.2)
Requirement already satisfied: rsa<5,>=3.1.4 in c:\users\hp\appdata\local\programs\python\python310\lib\site-packages (from google-auth[requests]<3.0.0,>=2.14.1->google-genai) (4.9.1)
Requirement already satisfied: certifi in c:\users\hp\appdata\local\programs\python\python310\lib\site-packages (from httpx<1.0.0,>=0.28.1->google-genai) (2025.11.12)
Collecting httpcore==1.*
  Downloading httpcore-1.0.9-py3-none-any.whl (78 kB)
Collecting h11>=0.16
  Downloading h11-0.16.0-py3-none-any.whl (37 kB)
Requirement already satisfied: pyasn1<0.7.0,>=0.6.1 in c:\users\hp\appdata\local\programs\python\python310\lib\site-packages (from pyasn1-modules>=0.2.1->google-auth[requests]<3.0.0,>=2.14.1->google-genai) (0.6.1)
Requirement already satisfied: pydantic-core==2.41.5 in c:\users\hp\appdata\local\programs\python\python310\lib\site-packages (from pydantic<3.0.0,>=2.9.0->google-genai) (2.41.5)
Requirement already satisfied: typing-inspection>=0.4.2 in c:\users\hp\appdata\local\programs\python\python310\lib\site-packages (from pydantic<3.0.0,>=2.9.0->google-genai) (0.4.2)
Requirement already satisfied: annotated-types>=0.6.0 in c:\users\hp\appdata\local\programs\python\python310\lib\site-packages (from pydantic<3.0.0,>=2.9.0->google-genai) (0.7.0)
Requirement already satisfied: six>=1.5 in c:\users\hp\appdata\local\programs\python\python310\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\hp\appdata\local\programs\python\python310\lib\site-packages (from requests<3.0.0,>=2.28.1->google-genai) (2.6.0)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\hp\appdata\local\programs\python\python310\lib\site-packages (from requests<3.0.0,>=2.28.1->google-genai) (3.4.4)
Requirement already satisfied: scipy>=1.8.0 in c:\users\hp\appdata\local\programs\python\python310\lib\site-packages (from scikit-learn->sklearn) (1.15.3)
Requirement already satisfied: joblib>=1.2.0 in c:\users\hp\appdata\local\programs\python\python310\lib\site-packages (from scikit-learn->sklearn) (1.5.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in c:\users\hp\appdata\local\programs\python\python310\lib\site-packages (from scikit-learn->sklearn) (3.6.0)
Using legacy 'setup.py install' for sklearn, since package 'wheel' is not installed.
Installing collected packages: rpds-py, h11, attrs, referencing, httpcore, anyio, websockets, tenacity, jsonschema-specifications, httpx, sklearn, jsonschema, google-genai
    Running setup.py install for sklearn: started
    Running setup.py install for sklearn: finished with status 'done'
Successfully installed anyio-4.12.0 attrs-25.4.0 google-genai-1.53.0 h11-0.16.0 httpcore-1.0.9 httpx-0.28.1 jsonschema-4.25.1 jsonschema-specifications-2025.9.1 referencing-0.37.0 rpds-py-0.30.0 sklearn-0.0 tenacity-9.1.2 websockets-15.0.1
Note: you may need to restart the kernel to use updated packages.

    ERROR: Command errored out with exit status 1:
     command: 'c:\Users\HP\AppData\Local\Programs\Python\Python310\python.exe' -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\HP\\AppData\\Local\\Temp\\pip-install-_a4o4ewr\\sklearn_379ed89a5f1b4d0ca0218879d47d2490\\setup.py'"'"'; __file__='"'"'C:\\Users\\HP\\AppData\\Local\\Temp\\pip-install-_a4o4ewr\\sklearn_379ed89a5f1b4d0ca0218879d47d2490\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\HP\AppData\Local\Temp\pip-pip-egg-info-rl3jfve7'
         cwd: C:\Users\HP\AppData\Local\Temp\pip-install-_a4o4ewr\sklearn_379ed89a5f1b4d0ca0218879d47d2490\
    Complete output (15 lines):
    The 'sklearn' PyPI package is deprecated, use 'scikit-learn'
    rather than 'sklearn' for pip commands.

    Here is how to fix this error in the main use cases:
    - use 'pip install scikit-learn' rather than 'pip install sklearn'
    - replace 'sklearn' by 'scikit-learn' in your pip requirements files
      (requirements.txt, setup.py, setup.cfg, Pipfile, etc ...)
    - if the 'sklearn' package is used by one of your dependencies,
      it would be great if you take some time to track which package uses
      'sklearn' instead of 'scikit-learn' and report it to their issue tracker
    - as a last resort, set the environment variable
      SKLEARN_ALLOW_DEPRECATED_SKLEARN_PACKAGE_INSTALL=True to avoid this error

    More information is available at
    https://github.com/scikit-learn/sklearn-pypi-package
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/46/1c/395a83ee7b2d2ad7a05b453872053d41449564477c81dc356f720b16eac4/sklearn-0.0.post12.tar.gz#sha256=54cff9e20839b7b202321178228af4d9388bedf78425d9299fd9ee170d68802e (from https://pypi.org/simple/sklearn/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
    ERROR: Command errored out with exit status 1:
     command: 'c:\Users\HP\AppData\Local\Programs\Python\Python310\python.exe' -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\HP\\AppData\\Local\\Temp\\pip-install-_a4o4ewr\\sklearn_e8c1f404c6d0491e879662ec712c98c5\\setup.py'"'"'; __file__='"'"'C:\\Users\\HP\\AppData\\Local\\Temp\\pip-install-_a4o4ewr\\sklearn_e8c1f404c6d0491e879662ec712c98c5\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\HP\AppData\Local\Temp\pip-pip-egg-info-9zm7e7w7'
         cwd: C:\Users\HP\AppData\Local\Temp\pip-install-_a4o4ewr\sklearn_e8c1f404c6d0491e879662ec712c98c5\
    Complete output (18 lines):
    The 'sklearn' PyPI package is deprecated, use 'scikit-learn'
    rather than 'sklearn' for pip commands.

    Here is how to fix this error in the main use cases:
    - use 'pip install scikit-learn' rather than 'pip install sklearn'
    - replace 'sklearn' by 'scikit-learn' in your pip requirements files
      (requirements.txt, setup.py, setup.cfg, Pipfile, etc ...)
    - if the 'sklearn' package is used by one of your dependencies,
      it would be great if you take some time to track which package uses
      'sklearn' instead of 'scikit-learn' and report it to their issue tracker
    - as a last resort, set the environment variable
      SKLEARN_ALLOW_DEPRECATED_SKLEARN_PACKAGE_INSTALL=True to avoid this error

    More information is available at
    https://github.com/scikit-learn/sklearn-pypi-package

    If the previous advice does not cover your use case, feel free to report it at
    https://github.com/scikit-learn/sklearn-pypi-package/issues/new
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/a4/0b/d1c703256cf293be77b7db44dbef62251fe02a97d0bef981f7120b0b0c0f/sklearn-0.0.post11.tar.gz#sha256=af035c4f0b970b7fc2d3856079aa1aa1032df3d7f65048a9d87114abf13c4629 (from https://pypi.org/simple/sklearn/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
    ERROR: Command errored out with exit status 1:
     command: 'c:\Users\HP\AppData\Local\Programs\Python\Python310\python.exe' -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\HP\\AppData\\Local\\Temp\\pip-install-_a4o4ewr\\sklearn_ce1cb340b276451795afaa0d22e824a9\\setup.py'"'"'; __file__='"'"'C:\\Users\\HP\\AppData\\Local\\Temp\\pip-install-_a4o4ewr\\sklearn_ce1cb340b276451795afaa0d22e824a9\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\HP\AppData\Local\Temp\pip-pip-egg-info-seqeb5a6'
         cwd: C:\Users\HP\AppData\Local\Temp\pip-install-_a4o4ewr\sklearn_ce1cb340b276451795afaa0d22e824a9\
    Complete output (18 lines):
    The 'sklearn' PyPI package is deprecated, use 'scikit-learn'
    rather than 'sklearn' for pip commands.

    Here is how to fix this error in the main use cases:
    - use 'pip install scikit-learn' rather than 'pip install sklearn'
    - replace 'sklearn' by 'scikit-learn' in your pip requirements files
      (requirements.txt, setup.py, setup.cfg, Pipfile, etc ...)
    - if the 'sklearn' package is used by one of your dependencies,
      it would be great if you take some time to track which package uses
      'sklearn' instead of 'scikit-learn' and report it to their issue tracker
    - as a last resort, set the environment variable
      SKLEARN_ALLOW_DEPRECATED_SKLEARN_PACKAGE_INSTALL=True to avoid this error

    More information is available at
    https://github.com/scikit-learn/sklearn-pypi-package

    If the previous advice does not cover your use case, feel free to report it at
    https://github.com/scikit-learn/sklearn-pypi-package/issues/new
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/b9/0e/b2a4cfaa9e12b9ca4c71507bc26d2c99d75de172c0088c9835a98cf146ff/sklearn-0.0.post10.tar.gz#sha256=d4cd5a2e64b3caaf82cd5e33c46884dfeec5ebf991710d9faeb4fe81cadb3ba6 (from https://pypi.org/simple/sklearn/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
    ERROR: Command errored out with exit status 1:
     command: 'c:\Users\HP\AppData\Local\Programs\Python\Python310\python.exe' -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\HP\\AppData\\Local\\Temp\\pip-install-_a4o4ewr\\sklearn_170dec727ebe44e28a42b29f6b1fb619\\setup.py'"'"'; __file__='"'"'C:\\Users\\HP\\AppData\\Local\\Temp\\pip-install-_a4o4ewr\\sklearn_170dec727ebe44e28a42b29f6b1fb619\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\HP\AppData\Local\Temp\pip-pip-egg-info-q9cpd5y_'
         cwd: C:\Users\HP\AppData\Local\Temp\pip-install-_a4o4ewr\sklearn_170dec727ebe44e28a42b29f6b1fb619\
    Complete output (18 lines):
    The 'sklearn' PyPI package is deprecated, use 'scikit-learn'
    rather than 'sklearn' for pip commands.

    Here is how to fix this error in the main use cases:
    - use 'pip install scikit-learn' rather than 'pip install sklearn'
    - replace 'sklearn' by 'scikit-learn' in your pip requirements files
      (requirements.txt, setup.py, setup.cfg, Pipfile, etc ...)
    - if the 'sklearn' package is used by one of your dependencies,
      it would be great if you take some time to track which package uses
      'sklearn' instead of 'scikit-learn' and report it to their issue tracker
    - as a last resort, set the environment variable
      SKLEARN_ALLOW_DEPRECATED_SKLEARN_PACKAGE_INSTALL=True to avoid this error

    More information is available at
    https://github.com/scikit-learn/sklearn-pypi-package

    If the previous advice does not cover your use case, feel free to report it at
    https://github.com/scikit-learn/sklearn-pypi-package/issues/new
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/28/86/207a003339023247fef1bb5bc9f5093140d17294b2f6d15bfcd4885e469e/sklearn-0.0.post9.tar.gz#sha256=1ff5864cf30489ee48a014fe8f4320d7bb59592392a4ef52ae9d7a37942615ac (from https://pypi.org/simple/sklearn/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
    ERROR: Command errored out with exit status 1:
     command: 'c:\Users\HP\AppData\Local\Programs\Python\Python310\python.exe' -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\HP\\AppData\\Local\\Temp\\pip-install-_a4o4ewr\\sklearn_3dcec4719a5044f0ba641af088ffa6e4\\setup.py'"'"'; __file__='"'"'C:\\Users\\HP\\AppData\\Local\\Temp\\pip-install-_a4o4ewr\\sklearn_3dcec4719a5044f0ba641af088ffa6e4\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\HP\AppData\Local\Temp\pip-pip-egg-info-jlq_ay7w'
         cwd: C:\Users\HP\AppData\Local\Temp\pip-install-_a4o4ewr\sklearn_3dcec4719a5044f0ba641af088ffa6e4\
    Complete output (18 lines):
    The 'sklearn' PyPI package is deprecated, use 'scikit-learn'
    rather than 'sklearn' for pip commands.

    Here is how to fix this error in the main use cases:
    - use 'pip install scikit-learn' rather than 'pip install sklearn'
    - replace 'sklearn' by 'scikit-learn' in your pip requirements files
      (requirements.txt, setup.py, setup.cfg, Pipfile, etc ...)
    - if the 'sklearn' package is used by one of your dependencies,
      it would be great if you take some time to track which package uses
      'sklearn' instead of 'scikit-learn' and report it to their issue tracker
    - as a last resort, set the environment variable
      SKLEARN_ALLOW_DEPRECATED_SKLEARN_PACKAGE_INSTALL=True to avoid this error

    More information is available at
    https://github.com/scikit-learn/sklearn-pypi-package

    If the previous advice does not cover your use case, feel free to report it at
    https://github.com/scikit-learn/sklearn-pypi-package/issues/new
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/70/ce/81aa643f3c43488c4a1e417e45f696a61e7ac82b57190fad3c310df2c07b/sklearn-0.0.post7.tar.gz#sha256=1c89020b364fdc3aa2839e0ae34e8f0b406669e4b5c2359dda3ac398f9c76874 (from https://pypi.org/simple/sklearn/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
    ERROR: Command errored out with exit status 1:
     command: 'c:\Users\HP\AppData\Local\Programs\Python\Python310\python.exe' -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\HP\\AppData\\Local\\Temp\\pip-install-_a4o4ewr\\sklearn_19b2954fb0ac46a0baec92e73732d2b3\\setup.py'"'"'; __file__='"'"'C:\\Users\\HP\\AppData\\Local\\Temp\\pip-install-_a4o4ewr\\sklearn_19b2954fb0ac46a0baec92e73732d2b3\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\HP\AppData\Local\Temp\pip-pip-egg-info-nu_25iia'
         cwd: C:\Users\HP\AppData\Local\Temp\pip-install-_a4o4ewr\sklearn_19b2954fb0ac46a0baec92e73732d2b3\
    Complete output (18 lines):
    The 'sklearn' PyPI package is deprecated, use 'scikit-learn'
    rather than 'sklearn' for pip commands.

    Here is how to fix this error in the main use cases:
    - use 'pip install scikit-learn' rather than 'pip install sklearn'
    - replace 'sklearn' by 'scikit-learn' in your pip requirements files
      (requirements.txt, setup.py, setup.cfg, Pipfile, etc ...)
    - if the 'sklearn' package is used by one of your dependencies,
      it would be great if you take some time to track which package uses
      'sklearn' instead of 'scikit-learn' and report it to their issue tracker
    - as a last resort, set the environment variable
      SKLEARN_ALLOW_DEPRECATED_SKLEARN_PACKAGE_INSTALL=True to avoid this error

    More information is available at
    https://github.com/scikit-learn/sklearn-pypi-package

    If the previous advice does not cover your use case, feel free to report it at
    https://github.com/scikit-learn/sklearn-pypi-package/issues/new
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/7a/93/e0e1b1e98f39dfca7ec9795cb46f6e09e88a2fd5d4a28e4b3d1f618a2aec/sklearn-0.0.post5.tar.gz#sha256=7377c714a03a79bbe9196f435db931fd2a6fa8c68514da7ed3a251fd08c52e2c (from https://pypi.org/simple/sklearn/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
    ERROR: Command errored out with exit status 1:
     command: 'c:\Users\HP\AppData\Local\Programs\Python\Python310\python.exe' -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\HP\\AppData\\Local\\Temp\\pip-install-_a4o4ewr\\sklearn_6d54010e751d46f68717014ab0a17f3d\\setup.py'"'"'; __file__='"'"'C:\\Users\\HP\\AppData\\Local\\Temp\\pip-install-_a4o4ewr\\sklearn_6d54010e751d46f68717014ab0a17f3d\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\HP\AppData\Local\Temp\pip-pip-egg-info-0wsvcq2j'
         cwd: C:\Users\HP\AppData\Local\Temp\pip-install-_a4o4ewr\sklearn_6d54010e751d46f68717014ab0a17f3d\
    Complete output (7 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\HP\AppData\Local\Temp\pip-install-_a4o4ewr\sklearn_6d54010e751d46f68717014ab0a17f3d\setup.py", line 10, in <module>
        LONG_DESCRIPTION = f.read()
      File "c:\Users\HP\AppData\Local\Programs\Python\Python310\lib\encodings\cp1252.py", line 23, in decode
        return codecs.charmap_decode(input,self.errors,decoding_table)[0]
    UnicodeDecodeError: 'charmap' codec can't decode byte 0x8f in position 7: character maps to <undefined>
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/99/b2/165110013aa66fae6fc13918ad0e9de4801e5f1691d371bf8b63328037e6/sklearn-0.0.post4.tar.gz#sha256=0e81ec9c32d4bb418e7be8f1ec1027d174975502dc84cbc4f4564b4cba31e674 (from https://pypi.org/simple/sklearn/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
    ERROR: Command errored out with exit status 1:
     command: 'c:\Users\HP\AppData\Local\Programs\Python\Python310\python.exe' -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\HP\\AppData\\Local\\Temp\\pip-install-_a4o4ewr\\sklearn_16dcdc7413f44c4083412fd8590651b1\\setup.py'"'"'; __file__='"'"'C:\\Users\\HP\\AppData\\Local\\Temp\\pip-install-_a4o4ewr\\sklearn_16dcdc7413f44c4083412fd8590651b1\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\HP\AppData\Local\Temp\pip-pip-egg-info-a98l3h5c'
         cwd: C:\Users\HP\AppData\Local\Temp\pip-install-_a4o4ewr\sklearn_16dcdc7413f44c4083412fd8590651b1\
    Complete output (18 lines):
    The 'sklearn' PyPI package is deprecated, use 'scikit-learn'
    rather than 'sklearn' for pip commands.

    Here is how to fix this error in the main use cases:
    - use 'pip install scikit-learn' rather than 'pip install sklearn'
    - replace 'sklearn' by 'scikit-learn' in your pip requirements files
      (requirements.txt, setup.py, setup.cfg, Pipfile, etc ...)
    - if the 'sklearn' package is used by one of your dependencies,
      it would be great if you take some time to track which package uses
      'sklearn' instead of 'scikit-learn' and report it to their issue tracker
    - as a last resort, set the environment variable
      SKLEARN_ALLOW_DEPRECATED_SKLEARN_PACKAGE_INSTALL=True to avoid this error

    More information is available at
    https://github.com/scikit-learn/sklearn-pypi-package

    If the previous advice does not cover your use case, feel free to report it at
    https://github.com/scikit-learn/sklearn-pypi-package/issues/new
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/db/1e/af4e9cded5093a92e60d4ae7149a02c7427661b2db66c8ea4d34b17864a2/sklearn-0.0.post1.tar.gz#sha256=76b9ed1623775168657b86b5fe966d45752e5c87f528de6240c38923b94147c5 (from https://pypi.org/simple/sklearn/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
WARNING: You are using pip version 21.2.3; however, version 25.3 is available.
You should consider upgrading via the 'c:\Users\HP\AppData\Local\Programs\Python\Python310\python.exe -m pip install --upgrade pip' command.

In [63]:

pip install openai

Collecting openai
  Downloading openai-2.9.0-py3-none-any.whl (1.0 MB)
Requirement already satisfied: typing-extensions<5,>=4.11 in c:\users\hp\appdata\local\programs\python\python310\lib\site-packages (from openai) (4.15.0)
Requirement already satisfied: anyio<5,>=3.5.0 in c:\users\hp\appdata\local\programs\python\python310\lib\site-packages (from openai) (4.12.0)
Collecting jiter<1,>=0.10.0
  Downloading jiter-0.12.0-cp310-cp310-win_amd64.whl (204 kB)
Requirement already satisfied: httpx<1,>=0.23.0 in c:\users\hp\appdata\local\programs\python\python310\lib\site-packages (from openai) (0.28.1)
Requirement already satisfied: pydantic<3,>=1.9.0 in c:\users\hp\appdata\local\programs\python\python310\lib\site-packages (from openai) (2.12.5)
Collecting distro<2,>=1.7.0
  Downloading distro-1.9.0-py3-none-any.whl (20 kB)
Collecting sniffio
  Downloading sniffio-1.3.1-py3-none-any.whl (10 kB)
Requirement already satisfied: tqdm>4 in c:\users\hp\appdata\local\programs\python\python310\lib\site-packages (from openai) (4.67.1)
Requirement already satisfied: exceptiongroup>=1.0.2 in c:\users\hp\appdata\roaming\python\python310\site-packages (from anyio<5,>=3.5.0->openai) (1.3.0)
Requirement already satisfied: idna>=2.8 in c:\users\hp\appdata\local\programs\python\python310\lib\site-packages (from anyio<5,>=3.5.0->openai) (3.11)
Requirement already satisfied: httpcore==1.* in c:\users\hp\appdata\local\programs\python\python310\lib\site-packages (from httpx<1,>=0.23.0->openai) (1.0.9)
Requirement already satisfied: certifi in c:\users\hp\appdata\local\programs\python\python310\lib\site-packages (from httpx<1,>=0.23.0->openai) (2025.11.12)
Requirement already satisfied: h11>=0.16 in c:\users\hp\appdata\local\programs\python\python310\lib\site-packages (from httpcore==1.*->httpx<1,>=0.23.0->openai) (0.16.0)
Requirement already satisfied: typing-inspection>=0.4.2 in c:\users\hp\appdata\local\programs\python\python310\lib\site-packages (from pydantic<3,>=1.9.0->openai) (0.4.2)
Requirement already satisfied: pydantic-core==2.41.5 in c:\users\hp\appdata\local\programs\python\python310\lib\site-packages (from pydantic<3,>=1.9.0->openai) (2.41.5)
Requirement already satisfied: annotated-types>=0.6.0 in c:\users\hp\appdata\local\programs\python\python310\lib\site-packages (from pydantic<3,>=1.9.0->openai) (0.7.0)
Requirement already satisfied: colorama in c:\users\hp\appdata\roaming\python\python310\site-packages (from tqdm>4->openai) (0.4.6)
Installing collected packages: sniffio, jiter, distro, openai
Successfully installed distro-1.9.0 jiter-0.12.0 openai-2.9.0 sniffio-1.3.1
Note: you may need to restart the kernel to use updated packages.

WARNING: You are using pip version 21.2.3; however, version 25.3 is available.
You should consider upgrading via the 'c:\Users\HP\AppData\Local\Programs\Python\Python310\python.exe -m pip install --upgrade pip' command.

###  Import Libraries

In [40]:
import pandas as pd
import json
from google import genai
from tqdm import tqdm
from jsonschema import validate, ValidationError
from sklearn.metrics import accuracy_score

### API Setup (Gemini)

In [ ]:
client = genai.Client(api_key="GENAI_API_KEY") 
MODEL_NAME = "gemini-2.5-flash"

In [ ]:
# from openai import OpenAI
# import json
# import re

# client = OpenAI(
#     api_key="OPENAI_API_KEY"
# )

# MODEL_NAME = "gpt-5-nano"

### LLM call Function

In [74]:
def call_llm(prompt):
    try:
        response = client.models.generate_content(
            model=MODEL_NAME,
            contents=prompt + "\n\nReturn ONLY valid JSON. No explanation. No extra text."
        )
        return response.text  
    except Exception as e:
        print("LLM Error:", str(e))
        return None

In [ ]:
# for openai api (limit reached for free versions)
def call_llm(prompt):
    try:
        full_prompt = prompt + "\n\nReturn ONLY valid JSON. No explanation. No extra text."
        
        response = client.responses.create(
            model=MODEL_NAME,
            input=full_prompt,
            store=True
        )
        
        output_text = response.output_text
        return output_text.strip()
    
    except Exception as e:
        print("LLM Error:", str(e))
        return None

### JSON Extractor

In [75]:
import re

def extract_json(text):
    if text is None:
        return None
    
    codeblock = re.search(r"```json(.*?)```", text, re.DOTALL)
    if codeblock:
        text = codeblock.group(1).strip()

    match = re.search(r"\{.*\}", text, re.DOTALL)
    if match:
        json_str = match.group(0)
        try:
            return json.loads(json_str)
        except:
            return None
    
    try:
        return json.loads(text)
    except:
        return None

### Load Dataset and sample it (200 rows)

In [76]:
df = pd.read_csv("data/yelp.csv")  

sample = df.sample(15, random_state=42).reset_index(drop=True)

sample.head()

,business_id,date,review_id,stars,text,type,user_id,cool,useful,funny
0,QVR7dsvBeg8xFt9B-vd1BA,22-07-2010,hwYVJs8Ko4PMjI19QcR57g,4,We got here around midnight last Friday... the...,review,90a6z--_CUrl84aCzZyPsg,5,5,2
1,24qSrF_XOrvaHDBy-gLIQg,22-01-2012,0mvthYPKb2ZmKhCADiKSmQ,5,Brought a friend from Louisiana here. She say...,review,9lJAj_2zCvP2jcEiRjF9oA,0,0,0
2,j0Uc-GuOe-x9_N_IK1KPpA,09-05-2009,XJHknNIecha6h0wkBSZB4w,3,"Every friday, my dad and I eat here. We order ...",review,0VfJi9Au0rVFVnPKcJpt3Q,0,0,0
3,RBiiGw8c7j-0a8nk35JO3w,22-12-2010,z6y3GRpYDqTznVe-0dn--Q,1,"My husband and I were really, really disappoin...",review,lwppVF0Yqkuwt-xaEuugqw,2,2,2
4,U8VA-RW6LYOhxR-Ygi6eDw,17-01-2011,vhWHdemMvsqVNv5zi2OMiA,5,Love this place! Was in phoenix 3 weeks for w...,review,Y2R_tlSk4lTHiLXTDsn1rg,0,1,0

### Prompt Version 1 — Basic Prompt
Simple direct instruction.  
Goal: evaluate baseline accuracy & JSON validity.

In [77]:
def prompt_v1(review):
    return f"""

Review: "{review}"

Return EXACT format:
{{
  "predicted_stars": <number between 1 and 5>,
  "explanation": "short explanation"
}}
"""

Running the Prompt V1 for data sample (200)

In [88]:
results_v1 = []

for i, row in tqdm(sample.iterrows(), total=len(sample)):
    full_prompt = prompt_v1(row["text"])
    raw = call_llm(full_prompt)

    try:
        parsed = extract_json(raw)
        predicted = parsed.get("predicted_stars", None)
        explanation = parsed.get("explanation", None)
        valid_json = True
    except:
        predicted = None
        valid_json = False
    
    results_v1.append({
        "actual": row["stars"],
        "pred": predicted,
        "json_valid": valid_json,
        "explanation":explanation,
        "actual text": row["text"]
    })

df_v1 = pd.DataFrame(results_v1)
df_v1

100%|██████████| 15/15 [00:46<00:00,  3.12s/it]

LLM Error: 429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. To monitor your current usage, head to: https://ai.dev/usage?tab=rate-limit. \n* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 10, model: gemini-2.5-flash\nPlease retry in 41.205853849s.', 'status': 'RESOURCE_EXHAUSTED', 'details': [{'@type': 'type.googleapis.com/google.rpc.Help', 'links': [{'description': 'Learn more about Gemini API quotas', 'url': 'https://ai.google.dev/gemini-api/docs/rate-limits'}]}, {'@type': 'type.googleapis.com/google.rpc.QuotaFailure', 'violations': [{'quotaMetric': 'generativelanguage.googleapis.com/generate_content_free_tier_requests', 'quotaId': 'GenerateRequestsPerMinutePerProjectPerModel-FreeTier', 'quotaDimensions': {'location': 'global', 'model': 'gemini-2.5-flash'}, 'quotaValue': '10'}]}, {'@type': 'type.googleapis.com/google.rpc.RetryInfo', 'retryDelay': '41s'}]}}

,actual,pred,json_valid,explanation,actual text
0,4,4.0,True,"Despite being empty late, the reviewer enjoyed...",We got here around midnight last Friday... the...
1,5,5.0,True,"The reviewer's friend, being from Louisiana, i...",Brought a friend from Louisiana here. She say...
2,3,4.0,True,The review indicates consistent satisfaction w...,"Every friday, my dad and I eat here. We order ..."
3,1,1.0,True,Dealership misdiagnosed a simple dirt buildup ...,"My husband and I were really, really disappoin..."
4,5,5.0,True,The reviewer expresses strong love for the pla...,Love this place! Was in phoenix 3 weeks for w...
5,4,5.0,True,The reviewer highlights great value due to low...,This hotel is in a good location for getting t...
6,4,5.0,True,"The review is overwhelmingly positive, praisin...",I love that this place has top seafood plates ...
7,4,5.0,True,"The review uses superlative terms ('awesome', ...",Awesome if you like ramen...even awesomer if y...
8,5,5.0,True,The review uses extremely positive language su...,"Great place for a ""home office"" morning. One o..."
9,1,1.0,True,The reviewer explicitly states '1 star for ser...,"1 star for service, but the food is not ok :( ..."
10,4,5.0,True,"The review is overwhelmingly positive, highlig...",Good food and able to manage a large group eas...
11,5,5.0,True,"The review is overwhelmingly positive, highlig...",This place is great!\nIf you talk to anybody t...
12,3,5.0,True,This is an extremely enthusiastic and positive...,Air Jordan! need I say more?
13,4,4.0,True,"The review is overwhelmingly positive, detaili...",There are many other reviews which extol the v...
14,5,NaN,False,"The review is overwhelmingly positive, detaili...",TJ was there for me when my water heater broke...

### Prompt Version 2 — Reasoning Prompt
We instruct the model to:
1. Think step-by-step internally
2. Output only final JSON

In [96]:
def prompt_v2(review):
    return f"""
Analyse the review step-by-step internally.
Do NOT reveal your reasoning.
Decide the most likely 1-5 star rating.

Review: "{review}"

Return strictly JSON:
{{
  "predicted_stars": <1-5>,
  "explanation": "<short reasoning>"
}}
"""

Runnint V2 Prompt for data sample

In [104]:
results_v2 = []

for i, row in tqdm(sample.iterrows(), total=len(sample)):
    full_prompt = prompt_v2(row["text"])
    raw = call_llm(full_prompt)

    try:
        parsed = extract_json(raw)
        predicted = parsed.get("predicted_stars", None)
        valid_json = True
    except:
        predicted = None
        valid_json = False
    
    results_v2.append({
        "actual": row["stars"],
        "pred": predicted,
        "json_valid": valid_json
    })

df_v2 = pd.DataFrame(results_v2)
df_v2

 93%|█████████▎| 14/15 [01:06<00:04,  4.19s/it]

LLM Error: 503 UNAVAILABLE. {'error': {'code': 503, 'message': 'The model is overloaded. Please try again later.', 'status': 'UNAVAILABLE'}}

100%|██████████| 15/15 [01:06<00:00,  4.43s/it]

LLM Error: 429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. To monitor your current usage, head to: https://ai.dev/usage?tab=rate-limit. \n* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 10, model: gemini-2.5-flash\nPlease retry in 21.81163002s.', 'status': 'RESOURCE_EXHAUSTED', 'details': [{'@type': 'type.googleapis.com/google.rpc.Help', 'links': [{'description': 'Learn more about Gemini API quotas', 'url': 'https://ai.google.dev/gemini-api/docs/rate-limits'}]}, {'@type': 'type.googleapis.com/google.rpc.QuotaFailure', 'violations': [{'quotaMetric': 'generativelanguage.googleapis.com/generate_content_free_tier_requests', 'quotaId': 'GenerateRequestsPerMinutePerProjectPerModel-FreeTier', 'quotaDimensions': {'location': 'global', 'model': 'gemini-2.5-flash'}, 'quotaValue': '10'}]}, {'@type': 'type.googleapis.com/google.rpc.RetryInfo', 'retryDelay': '21s'}]}}

    actual  pred  json_valid
0        4   5.0        True
1        5   5.0        True
2        3   5.0        True
3        1   1.0        True
4        5   5.0        True
5        4   5.0        True
6        4   5.0        True
7        4   5.0        True
8        5   5.0        True
9        1   1.0        True
10       4   5.0        True
11       5   5.0        True
12       3   5.0        True
13       4   NaN       False
14       5   NaN       False

In [99]:
df_v2

Empty DataFrame
Columns: []
Index: []

### Prompt Version 3 — Few-Shot Prompting
Provide examples of classifications.
Improves consistency and JSON formatting.

In [100]:
def prompt_v3(review):
    return f"""
Here are examples:

Example 1:
Review: "Food was cold and tasteless."
Output:
{{"predicted_stars": 1, "explanation": "Bad food quality."}}

Example 2:
Review: "Service was fast and friendly."
Output:
{{"predicted_stars": 5, "explanation": "Excellent service."}}

Now classify this review:

"{review}"

Return strictly valid JSON only.
"""

In [ ]:
# results_v3 = []

# for i, row in tqdm(sample.iterrows(), total=len(sample)):
#     full_prompt = prompt_v3(row["text"])
#     raw = call_llm(full_prompt)

#     try:
#         parsed = extract_json(raw)
#         predicted = parsed.get("predicted_stars", None)
#         explanation = parsed.get("explanation", None)
#         valid_json = True
#     except:
#         predicted = None
#         valid_json = False
    
#     results_v1.append({
#         "actual": row["stars"],
#         "pred": predicted,
#         "json_valid": valid_json,
#         "explanation":explanation,
#         "actual text": row["text"]
#     })

# df_v3 = pd.DataFrame(results_v3)
# df_v3

 80%|████████  | 12/15 [00:31<00:06,  2.04s/it]

LLM Error: 429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. To monitor your current usage, head to: https://ai.dev/usage?tab=rate-limit. \n* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 10, model: gemini-2.5-flash\nPlease retry in 27.780220545s.', 'status': 'RESOURCE_EXHAUSTED', 'details': [{'@type': 'type.googleapis.com/google.rpc.Help', 'links': [{'description': 'Learn more about Gemini API quotas', 'url': 'https://ai.google.dev/gemini-api/docs/rate-limits'}]}, {'@type': 'type.googleapis.com/google.rpc.QuotaFailure', 'violations': [{'quotaMetric': 'generativelanguage.googleapis.com/generate_content_free_tier_requests', 'quotaId': 'GenerateRequestsPerMinutePerProjectPerModel-FreeTier', 'quotaDimensions': {'location': 'global', 'model': 'gemini-2.5-flash'}, 'quotaValue': '10'}]}, {'@type': 'type.googleapis.com/google.rpc.RetryInfo', 'retryDelay': '27s'}]}}

 87%|████████▋ | 13/15 [00:31<00:03,  1.51s/it]

LLM Error: 429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. To monitor your current usage, head to: https://ai.dev/usage?tab=rate-limit. \n* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 10, model: gemini-2.5-flash\nPlease retry in 27.468593289s.', 'status': 'RESOURCE_EXHAUSTED', 'details': [{'@type': 'type.googleapis.com/google.rpc.Help', 'links': [{'description': 'Learn more about Gemini API quotas', 'url': 'https://ai.google.dev/gemini-api/docs/rate-limits'}]}, {'@type': 'type.googleapis.com/google.rpc.QuotaFailure', 'violations': [{'quotaMetric': 'generativelanguage.googleapis.com/generate_content_free_tier_requests', 'quotaId': 'GenerateRequestsPerMinutePerProjectPerModel-FreeTier', 'quotaDimensions': {'location': 'global', 'model': 'gemini-2.5-flash'}, 'quotaValue': '10'}]}, {'@type': 'type.googleapis.com/google.rpc.RetryInfo', 'retryDelay': '27s'}]}}

 93%|█████████▎| 14/15 [00:32<00:01,  1.15s/it]

LLM Error: 429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. To monitor your current usage, head to: https://ai.dev/usage?tab=rate-limit. \n* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 10, model: gemini-2.5-flash\nPlease retry in 27.174755408s.', 'status': 'RESOURCE_EXHAUSTED', 'details': [{'@type': 'type.googleapis.com/google.rpc.Help', 'links': [{'description': 'Learn more about Gemini API quotas', 'url': 'https://ai.google.dev/gemini-api/docs/rate-limits'}]}, {'@type': 'type.googleapis.com/google.rpc.QuotaFailure', 'violations': [{'quotaMetric': 'generativelanguage.googleapis.com/generate_content_free_tier_requests', 'quotaId': 'GenerateRequestsPerMinutePerProjectPerModel-FreeTier', 'quotaDimensions': {'location': 'global', 'model': 'gemini-2.5-flash'}, 'quotaValue': '10'}]}, {'@type': 'type.googleapis.com/google.rpc.RetryInfo', 'retryDelay': '27s'}]}}

100%|██████████| 15/15 [00:32<00:00,  2.17s/it]

LLM Error: 429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. To monitor your current usage, head to: https://ai.dev/usage?tab=rate-limit. \n* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 10, model: gemini-2.5-flash\nPlease retry in 26.852803423s.', 'status': 'RESOURCE_EXHAUSTED', 'details': [{'@type': 'type.googleapis.com/google.rpc.Help', 'links': [{'description': 'Learn more about Gemini API quotas', 'url': 'https://ai.google.dev/gemini-api/docs/rate-limits'}]}, {'@type': 'type.googleapis.com/google.rpc.QuotaFailure', 'violations': [{'quotaMetric': 'generativelanguage.googleapis.com/generate_content_free_tier_requests', 'quotaId': 'GenerateRequestsPerMinutePerProjectPerModel-FreeTier', 'quotaDimensions': {'location': 'global', 'model': 'gemini-2.5-flash'}, 'quotaValue': '10'}]}, {'@type': 'type.googleapis.com/google.rpc.RetryInfo', 'retryDelay': '26s'}]}}

Empty DataFrame
Columns: []
Index: []

0

In [ ]:
results_v3 = []

for i, row in tqdm(sample.iterrows(), total=len(sample)):
    full_prompt = prompt_v3(row["text"])
    raw = call_llm(full_prompt)

    try:
        parsed = extract_json(raw)
        predicted = parsed.get("predicted_stars", None)
        explanation = parsed.get("explanation", None)
        valid_json = True
    except:
        predicted = None
        valid_json = False
    
    results_v1.append({
        "actual": row["stars"],
        "pred": predicted,
        "json_valid": valid_json,
        "explanation":explanation,
        "actual text": row["text"]
    })

df_v3 = pd.DataFrame(results_v3)
df_v3

100%|██████████| 15/15 [00:40<00:00,  2.73s/it]

    actual  pred  json_valid
0        4     5        True
1        5     5        True
2        3     4        True
3        1     1        True
4        5     5        True
5        4     5        True
6        4     5        True
7        4     5        True
8        5     5        True
9        1     1        True
10       4     5        True
11       5     5        True
12       3     5        True
13       4     4        True
14       5     5        True

### Evaluation

In [85]:
def evaluate(df):
    accuracy = (df["actual"] == df["pred"]).mean()
    json_validity = df["json_valid"].mean()
    missing_preds = df["pred"].isna().sum()
    return accuracy, json_validity, missing_preds

In [86]:
metrics = {
    "Prompt V1": evaluate(df_v1),
    "Prompt V2": evaluate(df_v2),
    "Prompt V3": evaluate(df_v3)
}

metrics

{'Prompt V1': (np.float64(0.4), np.float64(0.7333333333333333), np.int64(4)),
 'Prompt V2': (np.float64(0.4666666666666667), np.float64(0.8), np.int64(3)),
 'Prompt V3': (np.float64(0.5333333333333333), np.float64(1.0), np.int64(0))}

In [87]:
eval_df = pd.DataFrame(metrics, index=["Accuracy", "JSON Validity", "Missing Predictions"])
eval_df.T

           Accuracy  JSON Validity  Missing Predictions
Prompt V1  0.400000       0.733333                  4.0
Prompt V2  0.466667       0.800000                  3.0
Prompt V3  0.533333       1.000000                  0.0

## Discussion of Results

The evaluation of the three prompt versions for Yelp review rating prediction shows a clear improvement in performance as the prompts become more structured and informative.

1. **Prompt V1 (Basic Direct Instruction)**  
   - **Accuracy:** 0.40  
   - **JSON Validity:** 0.73  
   - **Missing Predictions:** 4  
   
   This baseline prompt achieved moderate accuracy and JSON validity. While it instructs the model to return JSON, the lack of guidance for reasoning led to some malformed outputs and inconsistencies. A few predictions were missing due to the model not strictly following the format.

2. **Prompt V2 (Hidden Reasoning / Structured Instruction)**  
   - **Accuracy:** 0.47  
   - **JSON Validity:** 0.80  
   - **Missing Predictions:** 3  
   
   By instructing the model to analyze the review internally before predicting, Prompt V2 improved both accuracy and JSON validity. The structured instructions helped the model reason more carefully, resulting in fewer missing predictions and slightly higher consistency.

3. **Prompt V3 (Few-Shot Examples)**  
   - **Accuracy:** 0.53  
   - **JSON Validity:** 1.00  
   - **Missing Predictions:** 0  
   
   Providing explicit input-output examples allowed the model to follow the expected format precisely, achieving perfect JSON validity and no missing predictions. Accuracy also improved, as the examples guided the model in identifying key indicators for star ratings.


### Key Observations

- **Increasing structure improves reliability:** Adding reasoning instructions (V2) and examples (V3) led to better JSON compliance and fewer missing outputs.  
- **Few-shot examples enhance accuracy:** V3 demonstrates that showing the model explicit patterns for input and output helps it make better predictions.  
- **Trade-off between simplicity and performance:** While V1 is simple, its performance is limited. Adding guidance and examples increases complexity slightly but significantly improves results.

**Conclusion:**  
Structured prompting, particularly with few-shot examples, is the most effective approach for this rating prediction task. Prompt design directly affects accuracy, JSON validity, and the reliability of the model’s predictions. This demonstrates the importance of carefully crafting prompts when using LLMs for structured tasks.